package com.hexiaofei.sjzclient.dao.mapper;

import com.hexiaofei.sjzclient.domain.SjzBasePinyin;
import com.hexiaofei.sjzclient.domain.SjzBasePinyinExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SjzBasePinyinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @SelectProvider(type=SjzBasePinyinSqlProvider.class, method="countByExample")
    int countByExample(SjzBasePinyinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @DeleteProvider(type=SjzBasePinyinSqlProvider.class, method="deleteByExample")
    int deleteByExample(SjzBasePinyinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @Delete({
        "delete from sjz_base_pinyin",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @Insert({
        "insert into sjz_base_pinyin (id, pinYin, ",
        "pyCode)",
        "values (#{id,jdbcType=INTEGER}, #{pinYin,jdbcType=VARCHAR}, ",
        "#{pyCode,jdbcType=INTEGER})"
    })
    int insert(SjzBasePinyin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @InsertProvider(type=SjzBasePinyinSqlProvider.class, method="insertSelective")
    int insertSelective(SjzBasePinyin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @SelectProvider(type=SjzBasePinyinSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pinYin", property="pinYin", jdbcType=JdbcType.VARCHAR),
        @Result(column="pyCode", property="pyCode", jdbcType=JdbcType.INTEGER)
    })
    List<SjzBasePinyin> selectByExample(SjzBasePinyinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @Select({
        "select",
        "id, pinYin, pyCode",
        "from sjz_base_pinyin",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pinYin", property="pinYin", jdbcType=JdbcType.VARCHAR),
        @Result(column="pyCode", property="pyCode", jdbcType=JdbcType.INTEGER)
    })
    SjzBasePinyin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @UpdateProvider(type=SjzBasePinyinSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SjzBasePinyin record, @Param("example") SjzBasePinyinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @UpdateProvider(type=SjzBasePinyinSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SjzBasePinyin record, @Param("example") SjzBasePinyinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @UpdateProvider(type=SjzBasePinyinSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SjzBasePinyin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_base_pinyin
     *
     * @mbggenerated Wed Jun 19 23:07:20 CST 2019
     */
    @Update({
        "update sjz_base_pinyin",
        "set pinYin = #{pinYin,jdbcType=VARCHAR},",
          "pyCode = #{pyCode,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SjzBasePinyin record);

    @Select("select count(*) from sjz_base_pinyin")
    int selectCountByAll();
}