package com.shijianzhou.language.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SjzNlRelatePatternUnitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public SjzNlRelatePatternUnitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPatternNameIsNull() {
            addCriterion("patternName is null");
            return (Criteria) this;
        }

        public Criteria andPatternNameIsNotNull() {
            addCriterion("patternName is not null");
            return (Criteria) this;
        }

        public Criteria andPatternNameEqualTo(String value) {
            addCriterion("patternName =", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotEqualTo(String value) {
            addCriterion("patternName <>", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameGreaterThan(String value) {
            addCriterion("patternName >", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameGreaterThanOrEqualTo(String value) {
            addCriterion("patternName >=", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLessThan(String value) {
            addCriterion("patternName <", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLessThanOrEqualTo(String value) {
            addCriterion("patternName <=", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLike(String value) {
            addCriterion("patternName like", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotLike(String value) {
            addCriterion("patternName not like", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameIn(List<String> values) {
            addCriterion("patternName in", values, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotIn(List<String> values) {
            addCriterion("patternName not in", values, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameBetween(String value1, String value2) {
            addCriterion("patternName between", value1, value2, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotBetween(String value1, String value2) {
            addCriterion("patternName not between", value1, value2, "patternName");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoIsNull() {
            addCriterion("unitSerialNo is null");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoIsNotNull() {
            addCriterion("unitSerialNo is not null");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoEqualTo(Integer value) {
            addCriterion("unitSerialNo =", value, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoNotEqualTo(Integer value) {
            addCriterion("unitSerialNo <>", value, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoGreaterThan(Integer value) {
            addCriterion("unitSerialNo >", value, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("unitSerialNo >=", value, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoLessThan(Integer value) {
            addCriterion("unitSerialNo <", value, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoLessThanOrEqualTo(Integer value) {
            addCriterion("unitSerialNo <=", value, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoIn(List<Integer> values) {
            addCriterion("unitSerialNo in", values, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoNotIn(List<Integer> values) {
            addCriterion("unitSerialNo not in", values, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoBetween(Integer value1, Integer value2) {
            addCriterion("unitSerialNo between", value1, value2, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andUnitSerialNoNotBetween(Integer value1, Integer value2) {
            addCriterion("unitSerialNo not between", value1, value2, "unitSerialNo");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeIsNull() {
            addCriterion("regExpCode is null");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeIsNotNull() {
            addCriterion("regExpCode is not null");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeEqualTo(String value) {
            addCriterion("regExpCode =", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeNotEqualTo(String value) {
            addCriterion("regExpCode <>", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeGreaterThan(String value) {
            addCriterion("regExpCode >", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("regExpCode >=", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeLessThan(String value) {
            addCriterion("regExpCode <", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeLessThanOrEqualTo(String value) {
            addCriterion("regExpCode <=", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeLike(String value) {
            addCriterion("regExpCode like", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeNotLike(String value) {
            addCriterion("regExpCode not like", value, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeIn(List<String> values) {
            addCriterion("regExpCode in", values, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeNotIn(List<String> values) {
            addCriterion("regExpCode not in", values, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeBetween(String value1, String value2) {
            addCriterion("regExpCode between", value1, value2, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpCodeNotBetween(String value1, String value2) {
            addCriterion("regExpCode not between", value1, value2, "regExpCode");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternIsNull() {
            addCriterion("regExpPattern is null");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternIsNotNull() {
            addCriterion("regExpPattern is not null");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternEqualTo(String value) {
            addCriterion("regExpPattern =", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternNotEqualTo(String value) {
            addCriterion("regExpPattern <>", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternGreaterThan(String value) {
            addCriterion("regExpPattern >", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternGreaterThanOrEqualTo(String value) {
            addCriterion("regExpPattern >=", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternLessThan(String value) {
            addCriterion("regExpPattern <", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternLessThanOrEqualTo(String value) {
            addCriterion("regExpPattern <=", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternLike(String value) {
            addCriterion("regExpPattern like", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternNotLike(String value) {
            addCriterion("regExpPattern not like", value, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternIn(List<String> values) {
            addCriterion("regExpPattern in", values, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternNotIn(List<String> values) {
            addCriterion("regExpPattern not in", values, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternBetween(String value1, String value2) {
            addCriterion("regExpPattern between", value1, value2, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRegExpPatternNotBetween(String value1, String value2) {
            addCriterion("regExpPattern not between", value1, value2, "regExpPattern");
            return (Criteria) this;
        }

        public Criteria andRelateTypeIsNull() {
            addCriterion("relateType is null");
            return (Criteria) this;
        }

        public Criteria andRelateTypeIsNotNull() {
            addCriterion("relateType is not null");
            return (Criteria) this;
        }

        public Criteria andRelateTypeEqualTo(Short value) {
            addCriterion("relateType =", value, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeNotEqualTo(Short value) {
            addCriterion("relateType <>", value, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeGreaterThan(Short value) {
            addCriterion("relateType >", value, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("relateType >=", value, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeLessThan(Short value) {
            addCriterion("relateType <", value, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeLessThanOrEqualTo(Short value) {
            addCriterion("relateType <=", value, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeIn(List<Short> values) {
            addCriterion("relateType in", values, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeNotIn(List<Short> values) {
            addCriterion("relateType not in", values, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeBetween(Short value1, Short value2) {
            addCriterion("relateType between", value1, value2, "relateType");
            return (Criteria) this;
        }

        public Criteria andRelateTypeNotBetween(Short value1, Short value2) {
            addCriterion("relateType not between", value1, value2, "relateType");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("lastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("lastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("lastUpdateTime =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("lastUpdateTime <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("lastUpdateTime >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("lastUpdateTime <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("lastUpdateTime in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("lastUpdateTime not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNull() {
            addCriterion("descript is null");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNotNull() {
            addCriterion("descript is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptEqualTo(String value) {
            addCriterion("descript =", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotEqualTo(String value) {
            addCriterion("descript <>", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThan(String value) {
            addCriterion("descript >", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThanOrEqualTo(String value) {
            addCriterion("descript >=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThan(String value) {
            addCriterion("descript <", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThanOrEqualTo(String value) {
            addCriterion("descript <=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLike(String value) {
            addCriterion("descript like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotLike(String value) {
            addCriterion("descript not like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptIn(List<String> values) {
            addCriterion("descript in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotIn(List<String> values) {
            addCriterion("descript not in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptBetween(String value1, String value2) {
            addCriterion("descript between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotBetween(String value1, String value2) {
            addCriterion("descript not between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andUseStatusIsNull() {
            addCriterion("useStatus is null");
            return (Criteria) this;
        }

        public Criteria andUseStatusIsNotNull() {
            addCriterion("useStatus is not null");
            return (Criteria) this;
        }

        public Criteria andUseStatusEqualTo(Short value) {
            addCriterion("useStatus =", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusNotEqualTo(Short value) {
            addCriterion("useStatus <>", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusGreaterThan(Short value) {
            addCriterion("useStatus >", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("useStatus >=", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusLessThan(Short value) {
            addCriterion("useStatus <", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusLessThanOrEqualTo(Short value) {
            addCriterion("useStatus <=", value, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusIn(List<Short> values) {
            addCriterion("useStatus in", values, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusNotIn(List<Short> values) {
            addCriterion("useStatus not in", values, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusBetween(Short value1, Short value2) {
            addCriterion("useStatus between", value1, value2, "useStatus");
            return (Criteria) this;
        }

        public Criteria andUseStatusNotBetween(Short value1, Short value2) {
            addCriterion("useStatus not between", value1, value2, "useStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 04 21:29:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sjz_nl_relate_pattern_unit
     *
     * @mbggenerated Fri Oct 04 21:29:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}