spring:
  application:
    name: spring-zipkin-server

server:
  port: 4000
  tomcat:
    uri-encoding: utf-8

eureka:
  instance:
    hostname: spring-zipkin-server
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8686/eureka/