spring:
  application:
    name: service-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://51shijianzhou:3306/shijianzhou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 'lcyj'
    password: '000000'
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 3
      max-wait: 60000
      pool-prepared-statements: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-pool-prepared-statement-per-connection-size: 20

#showSql
logging:
  level:
    com.hexiaofei.provider0.dao.mapper : DEBUG