package com.hexiaofei.provider0.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hexiaofei.provider0.domain.SjzEventIndexTemp;
import com.hexiaofei.provider0.domain.SjzEventIndexTempExample.Criteria;
import com.hexiaofei.provider0.domain.SjzEventIndexTempExample.Criterion;
import com.hexiaofei.provider0.domain.SjzEventIndexTempExample;
import java.util.List;
import java.util.Map;

public class SjzEventIndexTempSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String countByExample(SjzEventIndexTempExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("sjz_event_index_temp");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String deleteByExample(SjzEventIndexTempExample example) {
        BEGIN();
        DELETE_FROM("sjz_event_index_temp");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String insertSelective(SjzEventIndexTemp record) {
        BEGIN();
        INSERT_INTO("sjz_event_index_temp");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getEventTime() != null) {
            VALUES("eventTime", "#{eventTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEventContent() != null) {
            VALUES("eventContent", "#{eventContent,jdbcType=VARCHAR}");
        }
        
        if (record.getEventType() != null) {
            VALUES("eventType", "#{eventType,jdbcType=TINYINT}");
        }
        
        if (record.getEventState() != null) {
            VALUES("eventState", "#{eventState,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPatternName() != null) {
            VALUES("patternName", "#{patternName,jdbcType=VARCHAR}");
        }
        
        if (record.getUnitSerialNo() != null) {
            VALUES("unitSerialNo", "#{unitSerialNo,jdbcType=INTEGER}");
        }
        
        if (record.getDomainName() != null) {
            VALUES("domainName", "#{domainName,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String selectByExample(SjzEventIndexTempExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("eventTime");
        SELECT("eventContent");
        SELECT("eventType");
        SELECT("eventState");
        SELECT("createTime");
        SELECT("patternName");
        SELECT("unitSerialNo");
        SELECT("domainName");
        FROM("sjz_event_index_temp");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SjzEventIndexTemp record = (SjzEventIndexTemp) parameter.get("record");
        SjzEventIndexTempExample example = (SjzEventIndexTempExample) parameter.get("example");
        
        BEGIN();
        UPDATE("sjz_event_index_temp");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getEventTime() != null) {
            SET("eventTime = #{record.eventTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEventContent() != null) {
            SET("eventContent = #{record.eventContent,jdbcType=VARCHAR}");
        }
        
        if (record.getEventType() != null) {
            SET("eventType = #{record.eventType,jdbcType=TINYINT}");
        }
        
        if (record.getEventState() != null) {
            SET("eventState = #{record.eventState,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPatternName() != null) {
            SET("patternName = #{record.patternName,jdbcType=VARCHAR}");
        }
        
        if (record.getUnitSerialNo() != null) {
            SET("unitSerialNo = #{record.unitSerialNo,jdbcType=INTEGER}");
        }
        
        if (record.getDomainName() != null) {
            SET("domainName = #{record.domainName,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sjz_event_index_temp");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("eventTime = #{record.eventTime,jdbcType=TIMESTAMP}");
        SET("eventContent = #{record.eventContent,jdbcType=VARCHAR}");
        SET("eventType = #{record.eventType,jdbcType=TINYINT}");
        SET("eventState = #{record.eventState,jdbcType=TINYINT}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("patternName = #{record.patternName,jdbcType=VARCHAR}");
        SET("unitSerialNo = #{record.unitSerialNo,jdbcType=INTEGER}");
        SET("domainName = #{record.domainName,jdbcType=VARCHAR}");
        
        SjzEventIndexTempExample example = (SjzEventIndexTempExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    public String updateByPrimaryKeySelective(SjzEventIndexTemp record) {
        BEGIN();
        UPDATE("sjz_event_index_temp");
        
        if (record.getEventTime() != null) {
            SET("eventTime = #{eventTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEventContent() != null) {
            SET("eventContent = #{eventContent,jdbcType=VARCHAR}");
        }
        
        if (record.getEventType() != null) {
            SET("eventType = #{eventType,jdbcType=TINYINT}");
        }
        
        if (record.getEventState() != null) {
            SET("eventState = #{eventState,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPatternName() != null) {
            SET("patternName = #{patternName,jdbcType=VARCHAR}");
        }
        
        if (record.getUnitSerialNo() != null) {
            SET("unitSerialNo = #{unitSerialNo,jdbcType=INTEGER}");
        }
        
        if (record.getDomainName() != null) {
            SET("domainName = #{domainName,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_event_index_temp
     *
     * @mbggenerated Fri Oct 04 21:47:35 CST 2019
     */
    protected void applyWhere(SjzEventIndexTempExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}