package com.hexiaofei.provider0.dao.mapper;

import com.hexiaofei.provider0.domain.SjzDomainInfo;
import com.hexiaofei.provider0.domain.SjzSpiderWebsite;
import com.hexiaofei.provider0.domain.SjzSpiderWebsiteExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SjzSpiderWebsiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @SelectProvider(type=SjzSpiderWebsiteSqlProvider.class, method="countByExample")
    int countByExample(SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @DeleteProvider(type=SjzSpiderWebsiteSqlProvider.class, method="deleteByExample")
    int deleteByExample(SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @Delete({
        "delete from sjz_spider_website",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @Insert({
        "insert into sjz_spider_website (id, websiteUrl, ",
        "websiteTitle, websiteDescri, ",
        "createTime, websiteContent)",
        "values (#{id,jdbcType=INTEGER}, #{websiteUrl,jdbcType=VARCHAR}, ",
        "#{websiteTitle,jdbcType=VARCHAR}, #{websiteDescri,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{websiteContent,jdbcType=LONGVARCHAR})"
    })
    int insert(SjzSpiderWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @InsertProvider(type=SjzSpiderWebsiteSqlProvider.class, method="insertSelective")
    int insertSelective(SjzSpiderWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @SelectProvider(type=SjzSpiderWebsiteSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="websiteUrl", property="websiteUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="websiteTitle", property="websiteTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="websiteDescri", property="websiteDescri", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="websiteContent", property="websiteContent", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<SjzSpiderWebsite> selectByExampleWithBLOBs(SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @SelectProvider(type=SjzSpiderWebsiteSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="websiteUrl", property="websiteUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="websiteTitle", property="websiteTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="websiteDescri", property="websiteDescri", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SjzSpiderWebsite> selectByExample(SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @Select({
        "select",
        "id, websiteUrl, websiteTitle, websiteDescri, createTime, websiteContent",
        "from sjz_spider_website",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="websiteUrl", property="websiteUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="websiteTitle", property="websiteTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="websiteDescri", property="websiteDescri", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="websiteContent", property="websiteContent", jdbcType=JdbcType.LONGVARCHAR)
    })
    SjzSpiderWebsite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @UpdateProvider(type=SjzSpiderWebsiteSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SjzSpiderWebsite record, @Param("example") SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @UpdateProvider(type=SjzSpiderWebsiteSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") SjzSpiderWebsite record, @Param("example") SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @UpdateProvider(type=SjzSpiderWebsiteSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SjzSpiderWebsite record, @Param("example") SjzSpiderWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @UpdateProvider(type=SjzSpiderWebsiteSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SjzSpiderWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @Update({
        "update sjz_spider_website",
        "set websiteUrl = #{websiteUrl,jdbcType=VARCHAR},",
          "websiteTitle = #{websiteTitle,jdbcType=VARCHAR},",
          "websiteDescri = #{websiteDescri,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "websiteContent = #{websiteContent,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(SjzSpiderWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_spider_website
     *
     * @mbggenerated Tue Jun 18 19:49:25 CST 2019
     */
    @Update({
        "update sjz_spider_website",
        "set websiteUrl = #{websiteUrl,jdbcType=VARCHAR},",
          "websiteTitle = #{websiteTitle,jdbcType=VARCHAR},",
          "websiteDescri = #{websiteDescri,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SjzSpiderWebsite record);

    @Select(" select count(*) from sjz_spider_website ")
    int selectCountByAll();

    @Select({
            " select ",
            " id, websiteUrl, websiteTitle, websiteDescri, createTime, websiteContent ",
            " from sjz_spider_website sdw ",
            " order by sdw.createTime desc ",
            " limit #{offset},#{pagesize} "
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="websiteUrl", property="websiteUrl", jdbcType=JdbcType.VARCHAR),
            @Result(column="websiteTitle", property="websiteTitle", jdbcType=JdbcType.VARCHAR),
            @Result(column="websiteDescri", property="websiteDescri", jdbcType=JdbcType.VARCHAR),
            @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="websiteContent", property="websiteContent", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<SjzSpiderWebsite> selectListByPaging(@Param("offset") int offset, @Param("pagesize")  int pageSize);

}