package com.lcyj.servicedemo.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.lcyj.servicedemo.model.SmsUserinfo;
import com.lcyj.servicedemo.model.SmsUserinfoExample.Criteria;
import com.lcyj.servicedemo.model.SmsUserinfoExample.Criterion;
import com.lcyj.servicedemo.model.SmsUserinfoExample;
import java.util.List;
import java.util.Map;

public class SmsUserinfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String countByExample(SmsUserinfoExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("sms_userinfo");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String deleteByExample(SmsUserinfoExample example) {
        BEGIN();
        DELETE_FROM("sms_userinfo");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String insertSelective(SmsUserinfo record) {
        BEGIN();
        INSERT_INTO("sms_userinfo");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("userId", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            VALUES("userName", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getIdCard() != null) {
            VALUES("idCard", "#{idCard,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            VALUES("sex", "#{sex,jdbcType=SMALLINT}");
        }
        
        if (record.getUserLevel() != null) {
            VALUES("userLevel", "#{userLevel,jdbcType=SMALLINT}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getMobileNo() != null) {
            VALUES("mobileNo", "#{mobileNo,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailStatus() != null) {
            VALUES("emailStatus", "#{emailStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getMobileNoStatus() != null) {
            VALUES("mobileNoStatus", "#{mobileNoStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String selectByExample(SmsUserinfoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("userId");
        SELECT("userName");
        SELECT("idCard");
        SELECT("sex");
        SELECT("userLevel");
        SELECT("email");
        SELECT("mobileNo");
        SELECT("emailStatus");
        SELECT("mobileNoStatus");
        SELECT("createTime");
        FROM("sms_userinfo");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SmsUserinfo record = (SmsUserinfo) parameter.get("record");
        SmsUserinfoExample example = (SmsUserinfoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("sms_userinfo");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("userId = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            SET("userName = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getIdCard() != null) {
            SET("idCard = #{record.idCard,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{record.sex,jdbcType=SMALLINT}");
        }
        
        if (record.getUserLevel() != null) {
            SET("userLevel = #{record.userLevel,jdbcType=SMALLINT}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getMobileNo() != null) {
            SET("mobileNo = #{record.mobileNo,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailStatus() != null) {
            SET("emailStatus = #{record.emailStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getMobileNoStatus() != null) {
            SET("mobileNoStatus = #{record.mobileNoStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sms_userinfo");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("userId = #{record.userId,jdbcType=VARCHAR}");
        SET("userName = #{record.userName,jdbcType=VARCHAR}");
        SET("idCard = #{record.idCard,jdbcType=VARCHAR}");
        SET("sex = #{record.sex,jdbcType=SMALLINT}");
        SET("userLevel = #{record.userLevel,jdbcType=SMALLINT}");
        SET("email = #{record.email,jdbcType=VARCHAR}");
        SET("mobileNo = #{record.mobileNo,jdbcType=VARCHAR}");
        SET("emailStatus = #{record.emailStatus,jdbcType=SMALLINT}");
        SET("mobileNoStatus = #{record.mobileNoStatus,jdbcType=SMALLINT}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        
        SmsUserinfoExample example = (SmsUserinfoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    public String updateByPrimaryKeySelective(SmsUserinfo record) {
        BEGIN();
        UPDATE("sms_userinfo");
        
        if (record.getUserId() != null) {
            SET("userId = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            SET("userName = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getIdCard() != null) {
            SET("idCard = #{idCard,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{sex,jdbcType=SMALLINT}");
        }
        
        if (record.getUserLevel() != null) {
            SET("userLevel = #{userLevel,jdbcType=SMALLINT}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getMobileNo() != null) {
            SET("mobileNo = #{mobileNo,jdbcType=VARCHAR}");
        }
        
        if (record.getEmailStatus() != null) {
            SET("emailStatus = #{emailStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getMobileNoStatus() != null) {
            SET("mobileNoStatus = #{mobileNoStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_userinfo
     *
     * @mbggenerated Sat Feb 22 22:44:10 CST 2020
     */
    protected void applyWhere(SmsUserinfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}