server:
  port: 7100
  tomcat:
    uri-encoding: utf-8

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8686/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     url: jdbc:mysql://lcyj88:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: 'lcyj'
     password: '000000'
  freemarker:
    enabled: false
  application:
    name: spring-feign-consumer
  zipkin:
    base-url: http://localhost:4000

hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 5000
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000 # \u8BF7\u6C42\u8D85\u65F6\u65F6\u957F\uFF0C\u7F3A\u7701\u4E3A1000
  threadpool:
      default:
        coreSize: 2 # \u8BF7\u6C42\u6700\u5927\u7EBF\u7A0B\u6570\uFF0C\u7F3A\u7701\u4E3A10

endpoints:
  shutdown:
    enabled: true                            # 启用shutdown
    sensitive: false                         # 禁用密码验证

feign:
   hystrix:
     enabled: true

