spring:
  application:
    name: EurekaServer

server:
  port: 8082

eureka:
  instance:
    hostname: eka3.com
  client:
    serviceUrl:
      defaultZone: http://eka1.com:8081/eureka/,http://eka2.com:8081/eureka/