spring:
  application:
    name: EurekaClient

server:
  port: 7001

eureka:
  instance:
    hostname: ceka1.com
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eka1.com:8080/eureka/,http://eka2.com:8081/eureka/