package com.hexiaofei.sjzclient.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hexiaofei.sjzclient.domain.MailAuthen;
import com.hexiaofei.sjzclient.domain.MailAuthenExample.Criteria;
import com.hexiaofei.sjzclient.domain.MailAuthenExample.Criterion;
import com.hexiaofei.sjzclient.domain.MailAuthenExample;
import java.util.List;
import java.util.Map;

public class MailAuthenSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String countByExample(MailAuthenExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("mail_authen");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String deleteByExample(MailAuthenExample example) {
        BEGIN();
        DELETE_FROM("mail_authen");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String insertSelective(MailAuthen record) {
        BEGIN();
        INSERT_INTO("mail_authen");
        
        if (record.getMailAuthenId() != null) {
            VALUES("mailAuthenId", "#{mailAuthenId,jdbcType=INTEGER}");
        }
        
        if (record.getMail() != null) {
            VALUES("mail", "#{mail,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            VALUES("sendTime", "#{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getValidCode() != null) {
            VALUES("validCode", "#{validCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String selectByExample(MailAuthenExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("mailAuthenId");
        } else {
            SELECT("mailAuthenId");
        }
        SELECT("mail");
        SELECT("sendTime");
        SELECT("validCode");
        SELECT("userId");
        FROM("mail_authen");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MailAuthen record = (MailAuthen) parameter.get("record");
        MailAuthenExample example = (MailAuthenExample) parameter.get("example");
        
        BEGIN();
        UPDATE("mail_authen");
        
        if (record.getMailAuthenId() != null) {
            SET("mailAuthenId = #{record.mailAuthenId,jdbcType=INTEGER}");
        }
        
        if (record.getMail() != null) {
            SET("mail = #{record.mail,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            SET("sendTime = #{record.sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getValidCode() != null) {
            SET("validCode = #{record.validCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("userId = #{record.userId,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("mail_authen");
        
        SET("mailAuthenId = #{record.mailAuthenId,jdbcType=INTEGER}");
        SET("mail = #{record.mail,jdbcType=VARCHAR}");
        SET("sendTime = #{record.sendTime,jdbcType=TIMESTAMP}");
        SET("validCode = #{record.validCode,jdbcType=VARCHAR}");
        SET("userId = #{record.userId,jdbcType=INTEGER}");
        
        MailAuthenExample example = (MailAuthenExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    public String updateByPrimaryKeySelective(MailAuthen record) {
        BEGIN();
        UPDATE("mail_authen");
        
        if (record.getMail() != null) {
            SET("mail = #{mail,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            SET("sendTime = #{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getValidCode() != null) {
            SET("validCode = #{validCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("userId = #{userId,jdbcType=INTEGER}");
        }
        
        WHERE("mailAuthenId = #{mailAuthenId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    protected void applyWhere(MailAuthenExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}