package com.hexiaofei.sjzclient.dao.mapper;

import com.hexiaofei.sjzclient.domain.MobileAuthen;
import com.hexiaofei.sjzclient.domain.MobileAuthenExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MobileAuthenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @SelectProvider(type=MobileAuthenSqlProvider.class, method="countByExample")
    int countByExample(MobileAuthenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @DeleteProvider(type=MobileAuthenSqlProvider.class, method="deleteByExample")
    int deleteByExample(MobileAuthenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @Delete({
        "delete from mobile_authen",
        "where mobileAuthenId = #{mobileAuthenId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer mobileAuthenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @Insert({
        "insert into mobile_authen (mobileAuthenId, mobile, ",
        "sendTime, validCode, ",
        "userId)",
        "values (#{mobileAuthenId,jdbcType=INTEGER}, #{mobile,jdbcType=VARCHAR}, ",
        "#{sendTime,jdbcType=TIMESTAMP}, #{validCode,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER})"
    })
    int insert(MobileAuthen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @InsertProvider(type=MobileAuthenSqlProvider.class, method="insertSelective")
    int insertSelective(MobileAuthen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @SelectProvider(type=MobileAuthenSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="mobileAuthenId", property="mobileAuthenId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="sendTime", property="sendTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="validCode", property="validCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER)
    })
    List<MobileAuthen> selectByExample(MobileAuthenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @Select({
        "select",
        "mobileAuthenId, mobile, sendTime, validCode, userId",
        "from mobile_authen",
        "where mobileAuthenId = #{mobileAuthenId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="mobileAuthenId", property="mobileAuthenId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="sendTime", property="sendTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="validCode", property="validCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER)
    })
    MobileAuthen selectByPrimaryKey(Integer mobileAuthenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @UpdateProvider(type=MobileAuthenSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MobileAuthen record, @Param("example") MobileAuthenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @UpdateProvider(type=MobileAuthenSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MobileAuthen record, @Param("example") MobileAuthenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @UpdateProvider(type=MobileAuthenSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MobileAuthen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbggenerated Sat Jun 06 15:27:15 CST 2020
     */
    @Update({
        "update mobile_authen",
        "set mobile = #{mobile,jdbcType=VARCHAR},",
          "sendTime = #{sendTime,jdbcType=TIMESTAMP},",
          "validCode = #{validCode,jdbcType=VARCHAR},",
          "userId = #{userId,jdbcType=INTEGER}",
        "where mobileAuthenId = #{mobileAuthenId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MobileAuthen record);
}