package com.hexiaofei.sjzclient.dao.mapper;

import com.hexiaofei.sjzclient.domain.SjzDomainSpiderTask;
import com.hexiaofei.sjzclient.domain.SjzDomainSpiderTaskExample;
import com.hexiaofei.sjzclient.domain.SjzDomainSpiderTaskExample.Criteria;
import com.hexiaofei.sjzclient.domain.SjzDomainSpiderTaskExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;


public class SjzDomainSpiderTaskSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String countByExample(SjzDomainSpiderTaskExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("sjz_domain_spider_task");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String deleteByExample(SjzDomainSpiderTaskExample example) {
        BEGIN();
        DELETE_FROM("sjz_domain_spider_task");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String insertSelective(SjzDomainSpiderTask record) {
        BEGIN();
        INSERT_INTO("sjz_domain_spider_task");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSpiderTaskName() != null) {
            VALUES("spiderTaskName", "#{spiderTaskName,jdbcType=VARCHAR}");
        }
        
        if (record.getWordCode() != null) {
            VALUES("wordCode", "#{wordCode,jdbcType=INTEGER}");
        }
        
        if (record.getPatternName() != null) {
            VALUES("patternName", "#{patternName,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaEn() != null) {
            VALUES("wordMetaEn", "#{wordMetaEn,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaZh() != null) {
            VALUES("wordMetaZh", "#{wordMetaZh,jdbcType=VARCHAR}");
        }
        
        if (record.getSpiderTaskType() != null) {
            VALUES("spiderTaskType", "#{spiderTaskType,jdbcType=SMALLINT}");
        }
        
        if (record.getSpiderTaskStatus() != null) {
            VALUES("spiderTaskStatus", "#{spiderTaskStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getSpiderTaskCreateTime() != null) {
            VALUES("spiderTaskCreateTime", "#{spiderTaskCreateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSpiderTaskDescription() != null) {
            VALUES("spiderTaskDescription", "#{spiderTaskDescription,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String selectByExample(SjzDomainSpiderTaskExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("spiderTaskName");
        SELECT("wordCode");
        SELECT("patternName");
        SELECT("wordMetaEn");
        SELECT("wordMetaZh");
        SELECT("spiderTaskType");
        SELECT("spiderTaskStatus");
        SELECT("spiderTaskCreateTime");
        SELECT("spiderTaskDescription");
        FROM("sjz_domain_spider_task");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SjzDomainSpiderTask record = (SjzDomainSpiderTask) parameter.get("record");
        SjzDomainSpiderTaskExample example = (SjzDomainSpiderTaskExample) parameter.get("example");
        
        BEGIN();
        UPDATE("sjz_domain_spider_task");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getSpiderTaskName() != null) {
            SET("spiderTaskName = #{record.spiderTaskName,jdbcType=VARCHAR}");
        }
        
        if (record.getWordCode() != null) {
            SET("wordCode = #{record.wordCode,jdbcType=INTEGER}");
        }
        
        if (record.getPatternName() != null) {
            SET("patternName = #{record.patternName,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaEn() != null) {
            SET("wordMetaEn = #{record.wordMetaEn,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaZh() != null) {
            SET("wordMetaZh = #{record.wordMetaZh,jdbcType=VARCHAR}");
        }
        
        if (record.getSpiderTaskType() != null) {
            SET("spiderTaskType = #{record.spiderTaskType,jdbcType=SMALLINT}");
        }
        
        if (record.getSpiderTaskStatus() != null) {
            SET("spiderTaskStatus = #{record.spiderTaskStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getSpiderTaskCreateTime() != null) {
            SET("spiderTaskCreateTime = #{record.spiderTaskCreateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSpiderTaskDescription() != null) {
            SET("spiderTaskDescription = #{record.spiderTaskDescription,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("sjz_domain_spider_task");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("spiderTaskName = #{record.spiderTaskName,jdbcType=VARCHAR}");
        SET("wordCode = #{record.wordCode,jdbcType=INTEGER}");
        SET("patternName = #{record.patternName,jdbcType=VARCHAR}");
        SET("wordMetaEn = #{record.wordMetaEn,jdbcType=VARCHAR}");
        SET("wordMetaZh = #{record.wordMetaZh,jdbcType=VARCHAR}");
        SET("spiderTaskType = #{record.spiderTaskType,jdbcType=SMALLINT}");
        SET("spiderTaskStatus = #{record.spiderTaskStatus,jdbcType=SMALLINT}");
        SET("spiderTaskCreateTime = #{record.spiderTaskCreateTime,jdbcType=TIMESTAMP}");
        SET("spiderTaskDescription = #{record.spiderTaskDescription,jdbcType=VARCHAR}");
        
        SjzDomainSpiderTaskExample example = (SjzDomainSpiderTaskExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String updateByPrimaryKeySelective(SjzDomainSpiderTask record) {
        BEGIN();
        UPDATE("sjz_domain_spider_task");
        
        if (record.getSpiderTaskName() != null) {
            SET("spiderTaskName = #{spiderTaskName,jdbcType=VARCHAR}");
        }
        
        if (record.getWordCode() != null) {
            SET("wordCode = #{wordCode,jdbcType=INTEGER}");
        }
        
        if (record.getPatternName() != null) {
            SET("patternName = #{patternName,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaEn() != null) {
            SET("wordMetaEn = #{wordMetaEn,jdbcType=VARCHAR}");
        }
        
        if (record.getWordMetaZh() != null) {
            SET("wordMetaZh = #{wordMetaZh,jdbcType=VARCHAR}");
        }
        
        if (record.getSpiderTaskType() != null) {
            SET("spiderTaskType = #{spiderTaskType,jdbcType=SMALLINT}");
        }
        
        if (record.getSpiderTaskStatus() != null) {
            SET("spiderTaskStatus = #{spiderTaskStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getSpiderTaskCreateTime() != null) {
            SET("spiderTaskCreateTime = #{spiderTaskCreateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSpiderTaskDescription() != null) {
            SET("spiderTaskDescription = #{spiderTaskDescription,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    protected void applyWhere(SjzDomainSpiderTaskExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}