package com.hexiaofei.sjzclient.dao.mapper;

import com.hexiaofei.sjzclient.domain.SjzDomainSpiderTask;
import com.hexiaofei.sjzclient.domain.SjzDomainSpiderTaskExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.cursor.Cursor;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SjzDomainSpiderTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @SelectProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="countByExample")
    int countByExample(SjzDomainSpiderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @DeleteProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="deleteByExample")
    int deleteByExample(SjzDomainSpiderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @Delete({
        "delete from sjz_domain_spider_task",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @Insert({
        "insert into sjz_domain_spider_task (id, spiderTaskName, ",
        "wordCode, patternName, ",
        "wordMetaEn, wordMetaZh, ",
        "spiderTaskType, spiderTaskStatus, ",
        "spiderTaskCreateTime, spiderTaskDescription)",
        "values (#{id,jdbcType=INTEGER}, #{spiderTaskName,jdbcType=VARCHAR}, ",
        "#{wordCode,jdbcType=INTEGER}, #{patternName,jdbcType=VARCHAR}, ",
        "#{wordMetaEn,jdbcType=VARCHAR}, #{wordMetaZh,jdbcType=VARCHAR}, ",
        "#{spiderTaskType,jdbcType=SMALLINT}, #{spiderTaskStatus,jdbcType=SMALLINT}, ",
        "#{spiderTaskCreateTime,jdbcType=TIMESTAMP}, #{spiderTaskDescription,jdbcType=VARCHAR})"
    })
    int insert(SjzDomainSpiderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @InsertProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="insertSelective")
    int insertSelective(SjzDomainSpiderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @SelectProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spiderTaskName", property="spiderTaskName", jdbcType=JdbcType.VARCHAR),
        @Result(column="wordCode", property="wordCode", jdbcType=JdbcType.INTEGER),
        @Result(column="patternName", property="patternName", jdbcType=JdbcType.VARCHAR),
        @Result(column="wordMetaEn", property="wordMetaEn", jdbcType=JdbcType.VARCHAR),
        @Result(column="wordMetaZh", property="wordMetaZh", jdbcType=JdbcType.VARCHAR),
        @Result(column="spiderTaskType", property="spiderTaskType", jdbcType=JdbcType.SMALLINT),
        @Result(column="spiderTaskStatus", property="spiderTaskStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="spiderTaskCreateTime", property="spiderTaskCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="spiderTaskDescription", property="spiderTaskDescription", jdbcType=JdbcType.VARCHAR)
    })
    List<SjzDomainSpiderTask> selectByExample(SjzDomainSpiderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @Select({
        "select",
        "id, spiderTaskName, wordCode, patternName, wordMetaEn, wordMetaZh, spiderTaskType, ",
        "spiderTaskStatus, spiderTaskCreateTime, spiderTaskDescription",
        "from sjz_domain_spider_task",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spiderTaskName", property="spiderTaskName", jdbcType=JdbcType.VARCHAR),
        @Result(column="wordCode", property="wordCode", jdbcType=JdbcType.INTEGER),
        @Result(column="patternName", property="patternName", jdbcType=JdbcType.VARCHAR),
        @Result(column="wordMetaEn", property="wordMetaEn", jdbcType=JdbcType.VARCHAR),
        @Result(column="wordMetaZh", property="wordMetaZh", jdbcType=JdbcType.VARCHAR),
        @Result(column="spiderTaskType", property="spiderTaskType", jdbcType=JdbcType.SMALLINT),
        @Result(column="spiderTaskStatus", property="spiderTaskStatus", jdbcType=JdbcType.SMALLINT),
        @Result(column="spiderTaskCreateTime", property="spiderTaskCreateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="spiderTaskDescription", property="spiderTaskDescription", jdbcType=JdbcType.VARCHAR)
    })
    SjzDomainSpiderTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @UpdateProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SjzDomainSpiderTask record, @Param("example") SjzDomainSpiderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @UpdateProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SjzDomainSpiderTask record, @Param("example") SjzDomainSpiderTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @UpdateProvider(type=SjzDomainSpiderTaskSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SjzDomainSpiderTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    @Update({
        "update sjz_domain_spider_task",
        "set spiderTaskName = #{spiderTaskName,jdbcType=VARCHAR},",
          "wordCode = #{wordCode,jdbcType=INTEGER},",
          "patternName = #{patternName,jdbcType=VARCHAR},",
          "wordMetaEn = #{wordMetaEn,jdbcType=VARCHAR},",
          "wordMetaZh = #{wordMetaZh,jdbcType=VARCHAR},",
          "spiderTaskType = #{spiderTaskType,jdbcType=SMALLINT},",
          "spiderTaskStatus = #{spiderTaskStatus,jdbcType=SMALLINT},",
          "spiderTaskCreateTime = #{spiderTaskCreateTime,jdbcType=TIMESTAMP},",
          "spiderTaskDescription = #{spiderTaskDescription,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SjzDomainSpiderTask record);

    @Select("select count(*) from sjz_domain_spider_task ")
    int selectCountByAll();

    @Select({
            "select",
            "id, spiderTaskName,patternName, wordCode, wordMetaEn, wordMetaZh, spiderTaskType, spiderTaskStatus, ",
            "spiderTaskCreateTime, spiderTaskDescription",
            "from sjz_domain_spider_task",
            " limit #{offset},#{pagesize} "
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="spiderTaskName", property="spiderTaskName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordCode", property="wordCode", jdbcType=JdbcType.INTEGER),
            @Result(column="patternName", property="patternName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordMetaEn", property="wordMetaEn", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordMetaZh", property="wordMetaZh", jdbcType=JdbcType.VARCHAR),
            @Result(column="spiderTaskType", property="spiderTaskType", jdbcType=JdbcType.SMALLINT),
            @Result(column="spiderTaskStatus", property="spiderTaskStatus", jdbcType=JdbcType.SMALLINT),
            @Result(column="spiderTaskCreateTime", property="spiderTaskCreateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="spiderTaskDescription", property="spiderTaskDescription", jdbcType=JdbcType.VARCHAR)
    })
    List<SjzDomainSpiderTask> selectListByPaging(@Param("offset") int offset, @Param("pagesize") int pageSize);


    @Select({
            "select",
            "id, spiderTaskName,patternName, wordCode, wordMetaEn, wordMetaZh, spiderTaskType, spiderTaskStatus, ",
            "spiderTaskCreateTime, spiderTaskDescription",
            "from sjz_domain_spider_task"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="spiderTaskName", property="spiderTaskName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordCode", property="wordCode", jdbcType=JdbcType.INTEGER),
            @Result(column="patternName", property="patternName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordMetaEn", property="wordMetaEn", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordMetaZh", property="wordMetaZh", jdbcType=JdbcType.VARCHAR),
            @Result(column="spiderTaskType", property="spiderTaskType", jdbcType=JdbcType.SMALLINT),
            @Result(column="spiderTaskStatus", property="spiderTaskStatus", jdbcType=JdbcType.SMALLINT),
            @Result(column="spiderTaskCreateTime", property="spiderTaskCreateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="spiderTaskDescription", property="spiderTaskDescription", jdbcType=JdbcType.VARCHAR)
    })
    Cursor<SjzDomainSpiderTask> selectCursorByAll();

    @Select({
            "select",
            "id, spiderTaskName,patternName, wordCode, wordMetaEn, wordMetaZh, spiderTaskType, spiderTaskStatus, ",
            "spiderTaskCreateTime, spiderTaskDescription",
            "from sjz_domain_spider_task"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="spiderTaskName", property="spiderTaskName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordCode", property="wordCode", jdbcType=JdbcType.INTEGER),
            @Result(column="patternName", property="patternName", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordMetaEn", property="wordMetaEn", jdbcType=JdbcType.VARCHAR),
            @Result(column="wordMetaZh", property="wordMetaZh", jdbcType=JdbcType.VARCHAR),
            @Result(column="spiderTaskType", property="spiderTaskType", jdbcType=JdbcType.SMALLINT),
            @Result(column="spiderTaskStatus", property="spiderTaskStatus", jdbcType=JdbcType.SMALLINT),
            @Result(column="spiderTaskCreateTime", property="spiderTaskCreateTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="spiderTaskDescription", property="spiderTaskDescription", jdbcType=JdbcType.VARCHAR)
    })
    List<SjzDomainSpiderTask> selectListByAll();
}