package com.hexiaofei.provider0.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SjzDomainSpiderTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public SjzDomainSpiderTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameIsNull() {
            addCriterion("spiderTaskName is null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameIsNotNull() {
            addCriterion("spiderTaskName is not null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameEqualTo(String value) {
            addCriterion("spiderTaskName =", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameNotEqualTo(String value) {
            addCriterion("spiderTaskName <>", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameGreaterThan(String value) {
            addCriterion("spiderTaskName >", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("spiderTaskName >=", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameLessThan(String value) {
            addCriterion("spiderTaskName <", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameLessThanOrEqualTo(String value) {
            addCriterion("spiderTaskName <=", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameLike(String value) {
            addCriterion("spiderTaskName like", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameNotLike(String value) {
            addCriterion("spiderTaskName not like", value, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameIn(List<String> values) {
            addCriterion("spiderTaskName in", values, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameNotIn(List<String> values) {
            addCriterion("spiderTaskName not in", values, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameBetween(String value1, String value2) {
            addCriterion("spiderTaskName between", value1, value2, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskNameNotBetween(String value1, String value2) {
            addCriterion("spiderTaskName not between", value1, value2, "spiderTaskName");
            return (Criteria) this;
        }

        public Criteria andWordCodeIsNull() {
            addCriterion("wordCode is null");
            return (Criteria) this;
        }

        public Criteria andWordCodeIsNotNull() {
            addCriterion("wordCode is not null");
            return (Criteria) this;
        }

        public Criteria andWordCodeEqualTo(Integer value) {
            addCriterion("wordCode =", value, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeNotEqualTo(Integer value) {
            addCriterion("wordCode <>", value, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeGreaterThan(Integer value) {
            addCriterion("wordCode >", value, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("wordCode >=", value, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeLessThan(Integer value) {
            addCriterion("wordCode <", value, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeLessThanOrEqualTo(Integer value) {
            addCriterion("wordCode <=", value, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeIn(List<Integer> values) {
            addCriterion("wordCode in", values, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeNotIn(List<Integer> values) {
            addCriterion("wordCode not in", values, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeBetween(Integer value1, Integer value2) {
            addCriterion("wordCode between", value1, value2, "wordCode");
            return (Criteria) this;
        }

        public Criteria andWordCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("wordCode not between", value1, value2, "wordCode");
            return (Criteria) this;
        }

        public Criteria andPatternNameIsNull() {
            addCriterion("patternName is null");
            return (Criteria) this;
        }

        public Criteria andPatternNameIsNotNull() {
            addCriterion("patternName is not null");
            return (Criteria) this;
        }

        public Criteria andPatternNameEqualTo(String value) {
            addCriterion("patternName =", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotEqualTo(String value) {
            addCriterion("patternName <>", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameGreaterThan(String value) {
            addCriterion("patternName >", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameGreaterThanOrEqualTo(String value) {
            addCriterion("patternName >=", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLessThan(String value) {
            addCriterion("patternName <", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLessThanOrEqualTo(String value) {
            addCriterion("patternName <=", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLike(String value) {
            addCriterion("patternName like", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotLike(String value) {
            addCriterion("patternName not like", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameIn(List<String> values) {
            addCriterion("patternName in", values, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotIn(List<String> values) {
            addCriterion("patternName not in", values, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameBetween(String value1, String value2) {
            addCriterion("patternName between", value1, value2, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotBetween(String value1, String value2) {
            addCriterion("patternName not between", value1, value2, "patternName");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnIsNull() {
            addCriterion("wordMetaEn is null");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnIsNotNull() {
            addCriterion("wordMetaEn is not null");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnEqualTo(String value) {
            addCriterion("wordMetaEn =", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnNotEqualTo(String value) {
            addCriterion("wordMetaEn <>", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnGreaterThan(String value) {
            addCriterion("wordMetaEn >", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnGreaterThanOrEqualTo(String value) {
            addCriterion("wordMetaEn >=", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnLessThan(String value) {
            addCriterion("wordMetaEn <", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnLessThanOrEqualTo(String value) {
            addCriterion("wordMetaEn <=", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnLike(String value) {
            addCriterion("wordMetaEn like", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnNotLike(String value) {
            addCriterion("wordMetaEn not like", value, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnIn(List<String> values) {
            addCriterion("wordMetaEn in", values, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnNotIn(List<String> values) {
            addCriterion("wordMetaEn not in", values, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnBetween(String value1, String value2) {
            addCriterion("wordMetaEn between", value1, value2, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaEnNotBetween(String value1, String value2) {
            addCriterion("wordMetaEn not between", value1, value2, "wordMetaEn");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhIsNull() {
            addCriterion("wordMetaZh is null");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhIsNotNull() {
            addCriterion("wordMetaZh is not null");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhEqualTo(String value) {
            addCriterion("wordMetaZh =", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhNotEqualTo(String value) {
            addCriterion("wordMetaZh <>", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhGreaterThan(String value) {
            addCriterion("wordMetaZh >", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhGreaterThanOrEqualTo(String value) {
            addCriterion("wordMetaZh >=", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhLessThan(String value) {
            addCriterion("wordMetaZh <", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhLessThanOrEqualTo(String value) {
            addCriterion("wordMetaZh <=", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhLike(String value) {
            addCriterion("wordMetaZh like", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhNotLike(String value) {
            addCriterion("wordMetaZh not like", value, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhIn(List<String> values) {
            addCriterion("wordMetaZh in", values, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhNotIn(List<String> values) {
            addCriterion("wordMetaZh not in", values, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhBetween(String value1, String value2) {
            addCriterion("wordMetaZh between", value1, value2, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andWordMetaZhNotBetween(String value1, String value2) {
            addCriterion("wordMetaZh not between", value1, value2, "wordMetaZh");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeIsNull() {
            addCriterion("spiderTaskType is null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeIsNotNull() {
            addCriterion("spiderTaskType is not null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeEqualTo(Short value) {
            addCriterion("spiderTaskType =", value, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeNotEqualTo(Short value) {
            addCriterion("spiderTaskType <>", value, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeGreaterThan(Short value) {
            addCriterion("spiderTaskType >", value, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("spiderTaskType >=", value, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeLessThan(Short value) {
            addCriterion("spiderTaskType <", value, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeLessThanOrEqualTo(Short value) {
            addCriterion("spiderTaskType <=", value, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeIn(List<Short> values) {
            addCriterion("spiderTaskType in", values, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeNotIn(List<Short> values) {
            addCriterion("spiderTaskType not in", values, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeBetween(Short value1, Short value2) {
            addCriterion("spiderTaskType between", value1, value2, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskTypeNotBetween(Short value1, Short value2) {
            addCriterion("spiderTaskType not between", value1, value2, "spiderTaskType");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusIsNull() {
            addCriterion("spiderTaskStatus is null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusIsNotNull() {
            addCriterion("spiderTaskStatus is not null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusEqualTo(Short value) {
            addCriterion("spiderTaskStatus =", value, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusNotEqualTo(Short value) {
            addCriterion("spiderTaskStatus <>", value, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusGreaterThan(Short value) {
            addCriterion("spiderTaskStatus >", value, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("spiderTaskStatus >=", value, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusLessThan(Short value) {
            addCriterion("spiderTaskStatus <", value, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusLessThanOrEqualTo(Short value) {
            addCriterion("spiderTaskStatus <=", value, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusIn(List<Short> values) {
            addCriterion("spiderTaskStatus in", values, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusNotIn(List<Short> values) {
            addCriterion("spiderTaskStatus not in", values, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusBetween(Short value1, Short value2) {
            addCriterion("spiderTaskStatus between", value1, value2, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskStatusNotBetween(Short value1, Short value2) {
            addCriterion("spiderTaskStatus not between", value1, value2, "spiderTaskStatus");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeIsNull() {
            addCriterion("spiderTaskCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeIsNotNull() {
            addCriterion("spiderTaskCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeEqualTo(Date value) {
            addCriterion("spiderTaskCreateTime =", value, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeNotEqualTo(Date value) {
            addCriterion("spiderTaskCreateTime <>", value, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeGreaterThan(Date value) {
            addCriterion("spiderTaskCreateTime >", value, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("spiderTaskCreateTime >=", value, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeLessThan(Date value) {
            addCriterion("spiderTaskCreateTime <", value, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("spiderTaskCreateTime <=", value, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeIn(List<Date> values) {
            addCriterion("spiderTaskCreateTime in", values, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeNotIn(List<Date> values) {
            addCriterion("spiderTaskCreateTime not in", values, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeBetween(Date value1, Date value2) {
            addCriterion("spiderTaskCreateTime between", value1, value2, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("spiderTaskCreateTime not between", value1, value2, "spiderTaskCreateTime");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionIsNull() {
            addCriterion("spiderTaskDescription is null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionIsNotNull() {
            addCriterion("spiderTaskDescription is not null");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionEqualTo(String value) {
            addCriterion("spiderTaskDescription =", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionNotEqualTo(String value) {
            addCriterion("spiderTaskDescription <>", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionGreaterThan(String value) {
            addCriterion("spiderTaskDescription >", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("spiderTaskDescription >=", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionLessThan(String value) {
            addCriterion("spiderTaskDescription <", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionLessThanOrEqualTo(String value) {
            addCriterion("spiderTaskDescription <=", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionLike(String value) {
            addCriterion("spiderTaskDescription like", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionNotLike(String value) {
            addCriterion("spiderTaskDescription not like", value, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionIn(List<String> values) {
            addCriterion("spiderTaskDescription in", values, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionNotIn(List<String> values) {
            addCriterion("spiderTaskDescription not in", values, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionBetween(String value1, String value2) {
            addCriterion("spiderTaskDescription between", value1, value2, "spiderTaskDescription");
            return (Criteria) this;
        }

        public Criteria andSpiderTaskDescriptionNotBetween(String value1, String value2) {
            addCriterion("spiderTaskDescription not between", value1, value2, "spiderTaskDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 19 21:48:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sjz_domain_spider_task
     *
     * @mbggenerated Sat Oct 19 21:48:37 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}