sharding:
  jdbc:
    datasource:
      names: ds_0,ds_1
      ds_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_0
        username: "root"
        password: ""
      ds_1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_1
        username: "root"
        password: ""
    config:
      sharding:
         tables:
            t_order:
              actualDataNodes: ds_${0..1}.t_order_${0..1}
              databaseStrategy:
                inline:
                  shardingColumn: user_id
                  algorithmExpression: ds_${user_id % 2}
              tableStrategy:
                inline:
                  shardingColumn: order_id
                  algorithmExpression: t_order_${order_id % 2}
            t_order_item:
              actualDataNodes: ds_${0..1}.t_order_item_${0..1}
              databaseStrategy:
                inline:
                  shardingColumn: user_id
                  algorithmExpression: ds_${user_id % 2}
              tableStrategy:
                inline:
                  shardingColumn: order_id
                  algorithmExpression: t_order_item_${order_id % 2}


