eureka:
  client:
    healthcheck:
      enabled: true                                                    # 开启心跳检测
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 100
    lease-renewal-interval-in-seconds: 200
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}