# \u4E3B\u4ECE\u914D\u7F6E
sharding:
  jdbc:
    datasource:
      names: ds_master_0,ds_master_1,ds_master_0_slave_0,ds_master_0_slave_1,ds_master_1_slave_0,ds_master_1_slave_1
      ds_master_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: "root"
        password: ""
      ds_master_0_slave_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: "root"
        password: ""
      ds_master_0_slave_1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: "root"
        password: ""
      ds_master_1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: "root"
        password: ""
      ds_master_1_slave_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: "root"
        password: ""
      ds_master_1_slave_1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: "root"
        password: ""
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-inline-expression: ds_${user_id % 2}
        tables:
          t_order:
            actualDataNodes: ds_${0..1}.t_order_${0..1}
            tableStrategy:
              inline:
                shardingColumn: order_id
                algorithmInlineExpression: t_order_${order_id % 2}
            keyGeneratorColumnName: order_id
          t_order_item:
            actualDataNodes: ds_${0..1}.t_order_item_${0..1}
            keyGeneratorColumnName: order_item_id
            tableStrategy:
              inline:
                shardingColumn: order_id
                algorithmInlineExpression: t_order_item_${order_id % 2}
        master-slave-rules:
          ds_0:
            masterDataSourceName: ds_master_0
            slaveDataSourceNames: ds_master_0_slave_0, ds_master_0_slave_1
          ds_1:
            masterDataSourceName: ds_master_1
            slaveDataSourceNames: ds_master_1_slave_0, ds_master_1_slave_1
