eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}